sudo: required
language: python
services:
- docker
script:
- docker build -t halo-sumologic .
- docker run -it --rm -v /tmp/halo-sumologic:/var/export halo-sumologic:latest cp -r /var/output/ /var/export/
